Successfully install deps in chroot

diff --git a/build_deps b/build_deps
--- a/build_deps
+++ b/build_deps
@@ -14,18 +14,17 @@ do
     
     # Build and install required software from the internal repository
     build_target $t libodb -1.4.0-1
-#    ./update_repo
+    ./update_repo
     
-#    mock -r $t install libodb 
-#    mock -r $t install libodb-devel
+    mock -r $t install libodb-devel
     
     
-#    if [ ! "$?" -eq $SUCCESS ]
-#    then
-#	echo "Problem installing libodb. Please check."
-#	echo "Dependency build aborted"
-#	exit
-#    fi
+    if [ ! "$?" -eq $SUCCESS ]
+    then
+	echo "Problem installing libodb. Please check."
+	echo "Dependency build aborted"
+	exit
+    fi
     
     
 #    for dep in "${deps[@]}"
